FROM python:3.12-slim


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


WORKDIR /app


RUN apt-get update \
    && apt-get install -y \
        build-essential \
        libpq-dev \
        libpango-1.0-0 \
        libpangoft2-1.0-0 \
        libcairo2 \
        libffi-dev \
        shared-mime-info \
    && rm -rf /var/lib/apt/lists/*


COPY requirements/ /app/requirements/


RUN pip install --upgrade pip \
    && pip install \
        --no-cache-dir \
        -r requirements/development.txt


COPY . /app/


EXPOSE 8000


CMD [
    "python",
    "manage.py",
    "runserver",
    "0.0.0.0:8000"
]